import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navber from '@/components/shared/Navber'
import Footer from '@/components/shared/Footer'
import AuthProvider from '@/providers/AuthProvider'
import ThemeProvider from '@/providers/ThemeProvider'
import TanstackProvider from '@/providers/TanstackProvider'
import SaearchProvider from '@/providers/SaearchProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Tulikona',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <TanstackProvider>
            <SaearchProvider>
              <AuthProvider>
                <Navber />
                {children}
                <Footer />
              </AuthProvider>
            </SaearchProvider>
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
